version: '3.6'



services:
  app:
    volumes:
      - ./app:/app
      # add configs if required
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - environments/.env.remote