version: '3.6'



services:
  app:
    volumes:
      - ./app:/app
      # add configs if required
      build:
        context: .
        dockerfile: Dockerfile
      command: >
        sh -c "python -m app.main"
      env_file:
        - environments/.env.remote
